spring.profiles.active: production

spring.devtools.livereload.enabled: false

spring.session.store-type: redis # Session store type.

---
spring:
  profiles: production

# TODO: add the credentials to your production redis
# preferably using environment variables

---
spring:
  profiles: development

#debug: true

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?verifyServerCertificate=false&useSSL=false&requireSSL=false&characterEncoding=utf8
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
  redis:
    password:
    host: localhost
    port: 6379
    database: 0
  # AOP
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: false # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
